# licensing-service.yml
spring:
  application:
    name: licensing-service

# Common licensing service properties
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8070/eureka/,http://eureka2:8072/eureka/,http://eureka3:8073/eureka/

