# organization-service.yml
spring:
  application:
    name: organization-service

# Common organization service properties
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8070/eureka/,http://eureka2:8072/eureka/,http://eureka3:8073/eureka/
